language: node_js
node_js:
- '12.22.10'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=blablacar)
  - secure: SpRDc/XxjrCJuvHj/xmL2k5C8uBzMSP9OL42N2cx6KoLnUdFOIXftjUDzAXVvGP9iiEWVe34l3cRMQAQ3cTPNWGpU1lBcQtK3T3bDVDxai0hfhH8qLKGjRjEPjNMYXmPum89TuFX6vIYzScgyvz/KUDfbMAYTOJhHSeIphFdVKmnT5V8uXO5R5i+rYcNRRROKsrOeq/d10yWRu1cCD9N4/G7cKIjfRkWzmrBXqQXMbP16Bhdg7DuJ5YBN3G+t2blpdLTTSAmSqiYMsjC4B4lFStRo0+jsvduYfkbarKLE1FSD2lTwRCosTtykvha5MlHs8cnQ+HrVPKnry7D1GFL6XoLChQflZN1tRLov4tf0OmvDPbMMkjT2t1wxGMgXCgZHsGAGh29x5Y+HvWBVAx5wLzOd2fjSLgYkuCLg2A60Rd/S+/lY8+ZDWozQX3Qy7nYO7JLbhISkTGCTFeuoFCp661xABKgbnOuv2evSeWFob8WJUIbLuZj6agbFVZIRv+RzX9O55bGjwGRtCaLsjjT7OsgyPGiib9PUuBo/krbAeVpt94wKHA3MS41BYAQyJLn1FEYahBl70x+9qNp/P6OiY7hWcGYp/fnK5l44EJRNB2qJbYhFXuncSukzdf5K+WTHk7UL5DjK1yzCBD5smS8qJ+pe6iC3NFCr0GJjTOrkAc=
  # MATTERMOST_HOOK_URL
  - secure: QH5YrlMbVMqK+/k8CwmSZ42MUCFlLxOcWvjrmXxJ4OdFcMSQc9TKS7xLVcuy8wGUeUG9F+R2yE15h4TRTnu76rPUsjgebdDajd0XJli7tm9tdWJWbBrr2t7aregvJ2zVZ+ppJVIcKxh0LZRqEqEIBet5r66qFSZvaL1Sa8nKvzbnMALGoDB9iihXogNUKTGkSBuigQSTbNmrhgnCkWB1KJ6hdza4OosaRZ63v6kyKRZABzh2KWfJDuKjJlfDcq1QEPz3LVYSZHDnmu4bghlOiPUAagx3zK/bn2IgugFd5WoDPoM5Dh+SeLKPOCmp2vkkV55M7mXQHAKvktfBkatddaTMtVy7sJQs6N6tnPtfFDLuIAJxA9EU1OmbQj1xc/WJrlwJhQObGvJKNzcUkr5ZBxaex+lMHxQ0YYFg2JY35WYRAQb20rqBGZWWMgeirAi2BKgD36pw6Js28VW0WletrjiC7GxUKcG8BGxfgoGIU/1CeRr6jyBP0LA7FNA1VCSRMKlnIb+EofO2QgmyylzGwTeUhOS5Ergsmdwt9JKcl2Be3vvZaklpMgBDEtrEJsBphYd8uKvtDFmp+gHH+btYqzX8UZMLvhlIHfSvhk0kCERvKhB43HAmVYQC89xLXsoPyKJ0vHfIQsiY7l8Q+ovd02FIVmDJlLKDSApweENDif8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_135bd4ae8fcb_key -iv $encrypted_135bd4ae8fcb_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
