language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "clxPZSR+Jd8WHGjvvxKiq2Yj9ZMClPwGf+IrADgkfpisGjNsSswkr1MuR7zB1455UBnP99kwptdN9c2Qsrv+uaN2IpE3l4E126NLtlgaJKJ7eNlFpqgNJVHRsv6sQc5WI0dReh76DFaqmg0dpmhnjCF3MqKKCFVIqIEHF3ANzMHn55Qj/i6Dmg2W/Rovwr4oWCkxoYbiQYYjBrfkIkXOZIjZf8+wiKJgPbZwH3+5ezZ0h0g8GsdoeIOhsjUUWFaS4j5CkyfDl6mpEbQTy146fqdv9hXHqtK9ADIKAHGLl8cBkfAECsxQKmRXkDAYZGGJwLJPf6e8smESBl32qYGPvIYh1HJDlKeacl1UZxr6lOoGIT8jDHhs/qAVsfXR/i8gTEXoUHmxvy3kFl11yrqq0/oFxcAULphFPZeUdmvyFPIPvkPEUz0Orsp1IKHGRFU99sMo5dStnOdJWzrbT01EWhsK9GRUftUjIGltPQ175uato0PUiIJpb4KfMo++WCvcDhB/dH5eXEd93WIG46aXNPNXBVo/wQNIZXWxgi9Z9FaVYwLjaSDwjgXq3aOS1Xvqc91pNB3IB+O7TLS7tovd18Bta604yEgbpgq8MF3GWVoGTfzPWgedxC37fIk1NSpULJ9jsDyuAdgbcwIIWkQ8JbNGkcdkV6Aiyhyx2wtjWQc="
    # Cozy REGISTRY_TOKEN
    - secure: "hXwYx2mgdEBUl1eVkPGwCMYWSdu3mli2UWz4u6LIAjk1nCx63y+LaMuQRQIL2WQNrVUAvNS+fKw+1tJw2dkjZj1S5otCVoBcTaTwJw/N8aOQmfeoPF/yHwERaw+w1j2KLRAgdHZABfCRds+x2GW8t7v9eEFjF6039SbpaWBHBzlVe+0dOj4CckDcP1f0ytBE4hXhdg3aVKmEtyCtLl9LenUmXiduD2kXRvj2aLut8iqozTJgGnLZt37IAclSZZz8EgeK+E/l2yNYL9B+e+duOqrBmxLDnt/RFOJWwnsMPU69gM4gBztTvpdjT5tIhw8CD1jTWUaiBAXY5bMK8CDlzj4Y5RTTVyaCTGB9coTUL678USb4huYDa6885Trmf4Ree7lsePwcpKT+5nopWqTu/uDUx1y4UCm5/P9TZ/FD9DYzcFhU0wSm/Z8M+VIgMeOf242CSLaiMJtiia4/PC65A3fJ3IiJzqtfkhdj9jeUfD9VpGpeNcuTryFmaMDvxzH94ET+YqKpVSfb7L08eKmo2VLAc2LNsJ7A/mrgmvb+4ztxsvKlR/giT5pxZBxQrn5zhhiZvSKNfeDDtYwQOgE/qIzRFSkLvMFGrpPOOvuPysYhgARmZJQ0NfbDa8AfejMXglBoGxUJKzgcKmhNtOyqioTiyk9PlZLuo8ahNLFkPxA="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  # publish dev versions
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  # publish on latest branch (will be removed when collect will use only the registry
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest && yarn deploy
    on:
      branch: prod
  # publish stable versions and beta versions based on tags
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      tags: true
