language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "iRCY8hPhhzM4kZCN8R1IQK5VRPt7fx+yWpxkxoastjyNmTqnVmrNvucZnuuUqa9dSnf+OWFIw2bkTVQRmPK3eiWUbqaWaXn7yxQ7rmPHJG0cUnOAjQlcmx2gzs4uSBDKqfnBJYI3rQEnQhGJ30K3iHKl6w+de8qbJLbhZKOYwCKIR4SJDTOSoOC6wONbAEPmv+jNo9+L4oMZkjDXNIdvgwAnKDPlT8xt4r6njlLpTdHjxvp1+6Sh4QS+BythzFdpTCnqApJdqSw9Gh0i9zLTH0OYV6x1+1NwoxoZ8fNJoGgg/L0uBzTv9S+L/Jruvwi8BIiYL5S45ezWi1Od7sFUdU9pSDbiOPQkKon3K10lniPviBWxissd9n4qkt5JHSB3ZSadrnge1+JzrD/D4giAy91R9gT/ju1tWlh3eE7I7ARyQHsXdr46CwvsXCV3vL0bFexldpR8ZoEQiT6mdRpjUdulpuXHRvIpJ3bv6X5+J27H3iOiV7Ik2qAPhpv6IVzpiPY/jtQBQJ/Yq6Nv7An99u2krQmWPHpAaMK9BXMW6iOW6GTgmytUWBIzTuFRDTiJkTKCcw3YXjHaDJSw/imH3rSuxAZAtfrolndP5uTxl+ayeW+2xAlfiIaUbzVzZ3sWeMoqfpHEakhiABwZBdd+/pdGfW8cQqOHZWTJUWwcVsQ="
    # Cozy REGISTRY_TOKEN
    - secure: "I6w8+cHOB8ASeRMsgjr0xBVgRpYqrY7HJ6jQhQW6fzSzxhfwZ8e+T23wCTa+ND/c6V8J2Hrk+hBj2kMOICG1QHvu5PHo3qX9AbcHz+z2c8KoZm8Yx1X1sQeRTGWqM+Ei+mwII/Qilm5eXzXLa9x+UJ45BEW3kXyAVmqfHTtDEAszAXgqHhB5GfkdC5bjl9busDwezcfai+oPD0HTNspu8DosJu3KMGwtyYNJyPD3dN6IoJpVAKsoZoBs4k62eOwi+tzZjFoEgkMeiI40zDr3pEWlykl1jvlfcrBbRAO8q6LsOMBcpKc68RrD/h8zD9EIOHUOimjZ4es1Cc8Kk7i1Kg8Rs4St7UYRg008C0vL7RZXffrvO5jZuOrKQhjzdzqdMy3PryaLeLE37VrbF3qfXBmQ+UUI6+imyFPmV1i4FiQDoOw9Pia44AYLW9nLIeIIrkh6rnh+zuFLDxRRFE4qBFVnTil0R4YKYcLVzfZsnCcsKOzISiQCrXITR1uqjzA457H5uPK4St+sj3JO+uAQBHMOoN2OhegjGcFl54sGY2BEeQ3mNJVDZ+jlXDgQuU9E0vICGeSRoMpduoMfpIYKA9F+ylCj/KJWF9aCHqPrk/ir6WgCpF+YEJSbRhW4KqJNZ0cMuF9oVUVN266x9L4vzV7rRj/v3E2pTRz5KZXBoro="

cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  # publish dev versions
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  # publish on latest branch (will be removed when collect will use only the registry
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest && yarn deploy
    on:
      branch: prod
  # publish stable versions and beta versions based on tags
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      tags: true
