language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "iRCY8hPhhzM4kZCN8R1IQK5VRPt7fx+yWpxkxoastjyNmTqnVmrNvucZnuuUqa9dSnf+OWFIw2bkTVQRmPK3eiWUbqaWaXn7yxQ7rmPHJG0cUnOAjQlcmx2gzs4uSBDKqfnBJYI3rQEnQhGJ30K3iHKl6w+de8qbJLbhZKOYwCKIR4SJDTOSoOC6wONbAEPmv+jNo9+L4oMZkjDXNIdvgwAnKDPlT8xt4r6njlLpTdHjxvp1+6Sh4QS+BythzFdpTCnqApJdqSw9Gh0i9zLTH0OYV6x1+1NwoxoZ8fNJoGgg/L0uBzTv9S+L/Jruvwi8BIiYL5S45ezWi1Od7sFUdU9pSDbiOPQkKon3K10lniPviBWxissd9n4qkt5JHSB3ZSadrnge1+JzrD/D4giAy91R9gT/ju1tWlh3eE7I7ARyQHsXdr46CwvsXCV3vL0bFexldpR8ZoEQiT6mdRpjUdulpuXHRvIpJ3bv6X5+J27H3iOiV7Ik2qAPhpv6IVzpiPY/jtQBQJ/Yq6Nv7An99u2krQmWPHpAaMK9BXMW6iOW6GTgmytUWBIzTuFRDTiJkTKCcw3YXjHaDJSw/imH3rSuxAZAtfrolndP5uTxl+ayeW+2xAlfiIaUbzVzZ3sWeMoqfpHEakhiABwZBdd+/pdGfW8cQqOHZWTJUWwcVsQ="
    # Cozy REGISTRY_TOKEN
    - secure: "Y5Ionvgq9RqkLSV6jwFnntddNVlj6Rr2xES16b9hwWjKeshBdvx5FepsmHJuE1X9m+YX33Hi+iZqfdjePGQ6KB6rR+Qb7rmpBy63nb1EOlqCRKVG/qrGD8eYOZLOT+fwzoc/fJr5GykHHyF/jdGog6HKa1uiL6kS83fNJBGD38v3NuPYGShBXt/ytkIJR71rPEMZEB2JxPiKxuyT2KjC+85GIVkwJLF9Eaa4Ik5NXEvOQroxyzAukHwDXsIUSRif0NKz8RazgagwP/EzrDWBqar42dtV5s6uiYNDcTKHQ/PV7wgEyg5e7ax8CNnO8SQTB7g5yyCluI+MVluXaDxhE1TSYl0pgk5IB+RZgXPBmqE4aPqvprHC3nkQjlWxRawWC3P1NHx/obt6a2CKsIc18vEshT1cXz7SaXq51J0XyvH7aEdFW1yjQEYIDRbOmIrtBScbfuOe+Zj5hTVDBbiQgclhU9XjUtMd+9U87wGpt1j6yhf4nHM8x3r9qnZgId04Om+rtbCIc2BmBoYjiHR0FDn/VE4UwhmIIUOR164AxIeMm/TGwG3UYGDSxcDJYfwqbC3qBh+xMNjcjwOXCM3WkL/6bkE8uygAySeZeTpTD9Y7qUEhC1xi91od3pZAN7OgT34/181eDPuLX9zG8d/9EMMBJAmYUIv4OuHqy8gDqxQ="

cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  # publish dev versions
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  # publish on latest branch (will be removed when collect will use only the registry
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest && yarn deploy
    on:
      branch: prod
  # publish stable versions and beta versions based on tags
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      tags: true
