language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "iRCY8hPhhzM4kZCN8R1IQK5VRPt7fx+yWpxkxoastjyNmTqnVmrNvucZnuuUqa9dSnf+OWFIw2bkTVQRmPK3eiWUbqaWaXn7yxQ7rmPHJG0cUnOAjQlcmx2gzs4uSBDKqfnBJYI3rQEnQhGJ30K3iHKl6w+de8qbJLbhZKOYwCKIR4SJDTOSoOC6wONbAEPmv+jNo9+L4oMZkjDXNIdvgwAnKDPlT8xt4r6njlLpTdHjxvp1+6Sh4QS+BythzFdpTCnqApJdqSw9Gh0i9zLTH0OYV6x1+1NwoxoZ8fNJoGgg/L0uBzTv9S+L/Jruvwi8BIiYL5S45ezWi1Od7sFUdU9pSDbiOPQkKon3K10lniPviBWxissd9n4qkt5JHSB3ZSadrnge1+JzrD/D4giAy91R9gT/ju1tWlh3eE7I7ARyQHsXdr46CwvsXCV3vL0bFexldpR8ZoEQiT6mdRpjUdulpuXHRvIpJ3bv6X5+J27H3iOiV7Ik2qAPhpv6IVzpiPY/jtQBQJ/Yq6Nv7An99u2krQmWPHpAaMK9BXMW6iOW6GTgmytUWBIzTuFRDTiJkTKCcw3YXjHaDJSw/imH3rSuxAZAtfrolndP5uTxl+ayeW+2xAlfiIaUbzVzZ3sWeMoqfpHEakhiABwZBdd+/pdGfW8cQqOHZWTJUWwcVsQ="
    # Cozy REGISTRY_TOKEN
    - secure: "PNp3MH7qK0XeNbrYMHhgG/3NTmUBJu0hg7ciy+Jfx3ElbkZN9s5xSUOPrMpVcZS/OO+JOAoV0eNnaahQ5vT1Y2poE3KmJOL68MAt8UsbJpdujoEH7Ds4qP3L6BrwoY3S4QEE7uTFvno19eHgDdt9qam6lnIiiVzt4qv2GqhUHYnvkXerhlZJ/ZF9IZKSJAKIdgQBpLozrbBDEhrbgiTTSx390ehMEd3syWMxbzjWzio4UcXFTBLRWjQoGhYbS/LU3PI7PCAxDTYcBgeluT3b2U4YksXlmjtRN50zf8sGwJrGN4/pnI2YFjZ9tI6H9EKEl7MTRVYesZVsSYgnBQ6WBGPR9ub+xPFC3yHZwdEsuFJyw24tRB95cXeUZuENvxL2D68R4pMxXy5qhHY3zKaW65UpJxJS+5NiwEffmy9kie7x2X1dHnBM8BSqkwJpIpe+jmLdFidxS6DPlgZqvXxV+X7baj30COGfRlyxDLXpkJ721+7F0bXHmuYHHj6e++AQVN3L5FslcZ9Gzwt2Xibl+OnnHBVuVnjGQzerMj6QrvZVhurU7bLpaBmYpoMxuK0ByYpL8WDJH/1Hz5POB+tKyroZNHWyEACltmzRiCF+Ppx61CeohoVozOSSgGmJRH13CzdbXZrFiKi45ZB6hz9ePiE3JU+ZO0YgX2DhIC6SvFw="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  # publish dev versions
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  # publish on latest branch (will be removed when collect will use only the registry
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest && yarn deploy
    on:
      branch: prod
  # publish stable versions and beta versions based on tags
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      tags: true
