language: node_js
node_js:
  - '8'
env:
  global:
    # Cozy REGISTRY_TOKEN
    - secure: "Y5Ionvgq9RqkLSV6jwFnntddNVlj6Rr2xES16b9hwWjKeshBdvx5FepsmHJuE1X9m+YX33Hi+iZqfdjePGQ6KB6rR+Qb7rmpBy63nb1EOlqCRKVG/qrGD8eYOZLOT+fwzoc/fJr5GykHHyF/jdGog6HKa1uiL6kS83fNJBGD38v3NuPYGShBXt/ytkIJR71rPEMZEB2JxPiKxuyT2KjC+85GIVkwJLF9Eaa4Ik5NXEvOQroxyzAukHwDXsIUSRif0NKz8RazgagwP/EzrDWBqar42dtV5s6uiYNDcTKHQ/PV7wgEyg5e7ax8CNnO8SQTB7g5yyCluI+MVluXaDxhE1TSYl0pgk5IB+RZgXPBmqE4aPqvprHC3nkQjlWxRawWC3P1NHx/obt6a2CKsIc18vEshT1cXz7SaXq51J0XyvH7aEdFW1yjQEYIDRbOmIrtBScbfuOe+Zj5hTVDBbiQgclhU9XjUtMd+9U87wGpt1j6yhf4nHM8x3r9qnZgId04Om+rtbCIc2BmBoYjiHR0FDn/VE4UwhmIIUOR164AxIeMm/TGwG3UYGDSxcDJYfwqbC3qBh+xMNjcjwOXCM3WkL/6bkE8uygAySeZeTpTD9Y7qUEhC1xi91od3pZAN7OgT34/181eDPuLX9zG8d/9EMMBJAmYUIv4OuHqy8gDqxQ="

cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  # publish dev versions
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  # publish stable versions and beta versions based on tags
  - provider: script
    repo: konnectors/blablacar
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      tags: true
